// samples/angular/src/app/app.component.ts
import {Component} from '@angular/core';
import {PillarboxComponent} from "./pillarbox.component";
@Component({
    selector: 'pb-root',
    imports: [
        PillarboxComponent
    ],
    template: `
    <header>
      <div class="logo-container">
        <img src="../assets/pb.webp" class="logo" alt="Pillarbox logo"/>
        <img src="../assets/angular.svg" class="logo" alt="Angular logo"/>
      </div>
      <h1>Pillarbox + Angular</h1>
    </header>
    <div class="player-container">
      <pb-player src="urn:rsi:video:1386617"></pb-player>
    </div>
  `
})
export class AppComponent {
}

// samples/react/src/App.jsx
import reactLogo from '/react.svg';
import pillarboxLogo from '/pb.webp';
import './index.css';
import Pillarbox from './pillarbox.jsx';

export default function App() {
  return (
    <>
      <header>
        <div className="logo-container">
          <img src={pillarboxLogo} className="logo" alt="React logo"/>
          <img src={reactLogo} className="logo ts" alt="Pillarbox logo"/>
        </div>
        <h1>Pillarbox + React</h1>
      </header>
      <div className="player-container">
        <Pillarbox src="urn:rts:video:14651145"/>
      </div>
    </>
  );
}
