// samples/react/src/App.jsx
import reactLogo from '/react.svg';
import pillarboxLogo from '/pb.webp';
import './index.css';
import Pillarbox from './pillarbox.jsx';

export default function App() {
  return (
    <>
      <header>
        <div className="logo-container">
          <img src={pillarboxLogo} className="logo" alt="React logo"/>
          <img src={reactLogo} className="logo ts" alt="Pillarbox logo"/>
        </div>
        <h1>Pillarbox + React</h1>
      </header>
      <div className="player-container">
        <Pillarbox src="urn:rts:video:14651145"/>
      </div>
    </>
  );
}

// samples/vue/src/App.vue
<script setup>
import Pillarbox from './components/Pillarbox.vue';
</script>

<template>
  <header>
    <div class="logo-container">
      <img src="/pb.webp" class="logo" alt="Pillarbox logo"/>
      <img src="/vue.svg" class="logo ts" alt="TypeScript logo"/>
    </div>
    <h1>Pillarbox + Vue</h1>
  </header>
  <div class="player-container">
    <Pillarbox src="urn:srf:video:c89ed8ad-d949-4ef0-81e5-3cf16dc11c25"/>
  </div>
</template>
