// samples/react/src/pillarbox.jsx
import { useEffect } from 'react';
import pillarbox from '@srgssr/pillarbox-web';
import '@srgssr/pillarbox-web/dist/pillarbox.min.css';

export default function Pillarbox({ src, type = 'srgssr/urn' }) {
  useEffect(() => {
    const player = pillarbox('main-player');
    player.src({ src, type });
  }, []);

  return <video id="main-player" className="video-js pillarbox-js" controls
                crossOrigin="anonymous"></video>;
}

// samples/vue/src/components/Pillarbox.vue
<script setup>
import { onMounted } from 'vue';
import pillarbox from '@srgssr/pillarbox-web';

// Define props
const props = defineProps({
  src: String,
  type: {
    type: String,
    default: 'srgssr/urn',
  },
});

onMounted(() => {
  const player = pillarbox('main-player');
  player.src({ src: props.src, type: props.type });
});
</script>

<template>
  <video id="main-player" class="video-js pillarbox-js" controls crossOrigin="anonymous"></video>
</template>

<style src='@srgssr/pillarbox-web/dist/pillarbox.min.css'>
</style>
